# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 프로개발자가 되기 위한 연구소
email: bdkk0209@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gatok is a minimal jekyll theme with a 3d menu bar. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
baseurl: /bdkk
permalink: /:title/

disqus-shortname: bdkk


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass: 
  style: compressed

analytics: UA-83979019-1

version: 1.0
 
gems: [jekyll-paginate, jekyll-seo-tag]

  
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

